# -*- coding: utf-8 -*-
"""recruit_vads.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zd5LrFvNJtdiukhv8FCXAnoCILazJFDB
"""

!pip install streamlit
import streamlit as st

# Define the layout of the app
st.set_page_config(layout="wide")

# Title of the application
st.title('Recruit VADS')

# Create columns for the input form and the results
col1, col2 = st.columns((1, 2))

# Input form in the first column
with col1:
    st.subheader("Job Opening Details")
    role = st.text_input("Role")
    experience = st.text_input("Experience")
    certifications = st.text_input("Certifications")
    skills = st.text_input("Skills")
    apply_button = st.button("Apply")

# Results area in the second column
with col2:
    st.subheader("Relevant candidates")
    # Placeholder for the table of candidates
    candidates_placeholder = st.empty()

# Logic for when the Apply button is clicked
if apply_button:
    # Normally here you'd have logic to search for candidates based on the input
    # For demonstration purposes, we'll use static data
    candidates_data = [
        {"Candidate name": "John Doe", "Contact details": "john@example.com", "Relevancy score": "95%"},
        # Add more candidate data here
    ]

    # Display candidates in the placeholder
    candidates_placeholder.table(candidates_data)